services:
  postgres-test:
    image: postgres:16-alpine
    container_name: transporte-test-db
    environment:
      - POSTGRES_DB=TransporteEscolarDb_Test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_TEST:-Testing2026}
    ports:
      - "5433:5432"
    volumes:
      - transporte-test-data:/var/lib/postgresql/data
    networks:
      - transporte-test-network

volumes:
  transporte-test-data:

networks:
  transporte-test-network:
    driver: bridge
