services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data_volume:/var/opt/mssql
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: TransporteEscolar.Api/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=${CONNECTIONSTRINGS__DEFAULT}
    restart: unless-stopped

volumes:
  sql_data_volume:
