// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransporteEscolar.Infrastructure.Persistence;

#nullable disable

namespace TransporteEscolar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218220626_AddTransporteToPasajeroHorarios")]
    partial class AddTransporteToPasajeroHorarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.GastoFijoTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("DiaDeAplicacion")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("EstaActivo", "FechaInicio");

                    b.ToTable("GastosFijosTemplates", (string)null);
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.GastoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GastoFijoTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("GastoFijoTemplateId");

                    b.HasIndex("Mes", "Anio");

                    b.ToTable("GastosMensuales", (string)null);
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Horarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Etiqueta = "8 San Patricio",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Etiqueta = "8 Boisdron",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Etiqueta = "9 Boisdron",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Etiqueta = "9 San Patricio",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Etiqueta = "12 San Patricio",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Etiqueta = "13 Boisdron Entrada",
                            Orden = 6
                        },
                        new
                        {
                            Id = 7,
                            Etiqueta = "13 Boisdron Salida",
                            Orden = 7
                        },
                        new
                        {
                            Id = 8,
                            Etiqueta = "16 San Patricio",
                            Orden = 8
                        },
                        new
                        {
                            Id = 9,
                            Etiqueta = "17 Boisdron",
                            Orden = 9
                        });
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.IngresoFijoTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("DiaDeAplicacion")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedioCobro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EstaActivo", "FechaInicio");

                    b.ToTable("IngresosFijosTemplates", (string)null);
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.IngresoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("EstadoCobro")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IngresoFijoTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("MedioCobro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IngresoFijoTemplateId");

                    b.HasIndex("Mes", "Anio");

                    b.ToTable("IngresosMensuales", (string)null);
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.PagoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoGenerado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TitularId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TitularId", "Mes", "Anio")
                        .IsUnique();

                    b.ToTable("PagosMensuales", (string)null);
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.PagoMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PagoMensualId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FechaPago");

                    b.HasIndex("PagoMensualId");

                    b.ToTable("PagosMovimientos", (string)null);
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.Pasajero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Colegio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GradoCurso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TitularId")
                        .HasColumnType("integer");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TitularId", "Nombre")
                        .IsUnique();

                    b.ToTable("Pasajeros", (string)null);
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.PasajeroHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HorarioId")
                        .HasColumnType("integer");

                    b.Property<int>("PasajeroId")
                        .HasColumnType("integer");

                    b.Property<int>("Prioridad")
                        .HasColumnType("integer");

                    b.Property<byte>("Transporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("Id");

                    b.HasIndex("HorarioId");

                    b.HasIndex("PasajeroId", "HorarioId")
                        .IsUnique();

                    b.ToTable("PasajeroHorarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_PasajeroHorarios_Transporte", "\"Transporte\" IN (1,2)");
                        });
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.ReinscripcionPasajero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PasajeroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PasajeroId", "Anio")
                        .IsUnique();

                    b.ToTable("ReinscripcionesPasajeros", (string)null);
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.Titular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoMensualPactado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Apellido");

                    b.ToTable("Titulares", (string)null);
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.TitularTelefono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroE164")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TitularId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TitularId", "NumeroE164")
                        .IsUnique();

                    b.ToTable("TitularesTelefonos", (string)null);
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.GastoMensual", b =>
                {
                    b.HasOne("TransporteEscolar.Domain.Entities.GastoFijoTemplate", "GastoFijoTemplate")
                        .WithMany("GastosGenerados")
                        .HasForeignKey("GastoFijoTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GastoFijoTemplate");
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.IngresoMensual", b =>
                {
                    b.HasOne("TransporteEscolar.Domain.Entities.IngresoFijoTemplate", "IngresoFijoTemplate")
                        .WithMany("IngresosGenerados")
                        .HasForeignKey("IngresoFijoTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IngresoFijoTemplate");
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.PagoMensual", b =>
                {
                    b.HasOne("TransporteEscolar.Domain.Entities.Titular", "Titular")
                        .WithMany()
                        .HasForeignKey("TitularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Titular");
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.PagoMovimiento", b =>
                {
                    b.HasOne("TransporteEscolar.Domain.Entities.PagoMensual", "PagoMensual")
                        .WithMany("Movimientos")
                        .HasForeignKey("PagoMensualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PagoMensual");
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.Pasajero", b =>
                {
                    b.HasOne("TransporteEscolar.Domain.Entities.Titular", "Titular")
                        .WithMany()
                        .HasForeignKey("TitularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Titular");
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.PasajeroHorario", b =>
                {
                    b.HasOne("TransporteEscolar.Domain.Entities.Horario", "Horario")
                        .WithMany("PasajeroHorarios")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransporteEscolar.Domain.Entities.Pasajero", "Pasajero")
                        .WithMany("PasajeroHorarios")
                        .HasForeignKey("PasajeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horario");

                    b.Navigation("Pasajero");
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.ReinscripcionPasajero", b =>
                {
                    b.HasOne("TransporteEscolar.Domain.Entities.Pasajero", "Pasajero")
                        .WithMany("Reinscripciones")
                        .HasForeignKey("PasajeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pasajero");
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.TitularTelefono", b =>
                {
                    b.HasOne("TransporteEscolar.Domain.Entities.Titular", "Titular")
                        .WithMany("Telefonos")
                        .HasForeignKey("TitularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Titular");
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.GastoFijoTemplate", b =>
                {
                    b.Navigation("GastosGenerados");
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.Horario", b =>
                {
                    b.Navigation("PasajeroHorarios");
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.IngresoFijoTemplate", b =>
                {
                    b.Navigation("IngresosGenerados");
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.PagoMensual", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.Pasajero", b =>
                {
                    b.Navigation("PasajeroHorarios");

                    b.Navigation("Reinscripciones");
                });

            modelBuilder.Entity("TransporteEscolar.Domain.Entities.Titular", b =>
                {
                    b.Navigation("Telefonos");
                });
#pragma warning restore 612, 618
        }
    }
}
